services:
  default:
    build: .
    volumes:
      - .:/workspace
      - ~/.cache/pypoetry:/root/.cache/pypoetry
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
